name: Linux Build arm64
on: workflow_dispatch
jobs:
  build-linux-arm64:
    runs-on: ubuntu-20.04
    name: Build on linux-arm64
    steps:
      - name: Update binaries
        run: |
          sudo apt update || true
          sudo apt install -y libuv1-dev
          sudo apt install -y g++-arm64-linux-gnu || true  # Install cross-compiler for ARM64
          git clone --recursive https://github.com/RajaSunrise/socketify-extra.git
          cd socketify-extra/socketify_extra/native
          # Cross-compile for ARM64
          GOOS=linux GOARCH=arm64 make linux
          cd ../
          git add libsocketify_linux_arm64.so
          git config --global user.email "rajasunsrise@gmail.com"
          git config --global user.name "RajaSunrise"
          git commit -m "[GitHub Actions] Updated linux-arm64 binaries" || true
          git push "https://RajaSunrise:${{ secrets.BUILDTOKEN }}@github.com/RajaSunrise/socketify-extra.git"
